// File recommented by recomment.cpp
// on Dec  9 2019 at 10:14:05.
//
// -*- mode: C; tab-width: 2 ; indent-tabs-mode: nil -*-
//
//  Universal Keyboard Project
//  ASDF firmware - small, fast, and simple keyboard encoder.
//
//  asdf.c
//
// This file contains code for:
// - the main scan code and key handler routines
// - key matrix declarations and keyboard state variables not delegated
//   elsewhere.
// - Key debouncing logic and data stuctures
// - dispatch of special functions bound to keys.
//
// Copyright 2019 David Fenyes
//
//  This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

#include "asdf.h"
#include "asdf_arch.h"
#include "asdf_ascii.h"
#include "asdf_ring.h"
#include "asdf_platform.h"
#include "asdf_actions.h"
#include "asdf_keyboard.h"
#include "asdf_keymaps.h"
#include "asdf_modifiers.h"
#include "asdf_physical.h"
#include "asdf_repeat.h"
#include "asdf_virtual.h"
#include <stdint.h>
#include <stdio.h>

// All keyboard state is held in the asdf_t passed to each function (see
// asdf_keyboard.h).

// Position of no key, for last_key_row/last_key_col when no key is repeating.
#define NO_KEY_POSITION 0xff

static void asdf_scan_elapsed_r(asdf_t *kb, uint8_t elapsed);

// PROCEDURE: asdf_put_code_r
// INPUTS: (asdf_t *) kb - keyboard
//         (asdf_keycode_t) code: code to be buffered for output
// OUTPUTS: returns TRUE (nonzero) if the code was queued, FALSE (0) if the
// keycode queue was full.
//
// DESCRIPTION: Takes a keycode argument and buffers for output.
//
// NOTES: If the queue is full, the code is dropped and counted.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
uint8_t asdf_put_code_r(asdf_t *kb, asdf_keycode_t code) {
    return asdf_ring_put(&kb->keycodes, code);
}

// PROCEDURE: asdf_putc_r
// INPUTS: (asdf_t *) kb - keyboard
//         (char) c: character to be buffered for output
// OUTPUTS: returns c, or EOF if the message queue had no room for it.
//
// DESCRIPTION: Takes a character generated by the system and buffers for
// output. A newline is sent as CR LF.
//
// NOTES: CR LF is queued as a unit: if both do not fit, neither is queued, so
// a message never ends with a partial line ending. Characters that do not fit
// are dropped and counted.
//
// SCOPE: public
//
// COMPLEXITY: 3
//
int asdf_putc_r(asdf_t *kb, char c) {
    uint8_t queued = ('\n' == c) ? asdf_ring_put_pair(&kb->messages, '\r', '\n')
                                 : asdf_ring_put(&kb->messages, (asdf_keycode_t)c);
    return queued ? (int)c : EOF;
}

// PROCEDURE: asdf_install_platform_r
// INPUTS: (asdf_t *) kb - keyboard
//         (const asdf_platform_t *) platform - platform to use, or NULL for the
//         keyboard's base platform
// OUTPUTS: none
//
// DESCRIPTION: Selects the platform through which the key matrix is read,
// codes are sent, and outputs are driven. Keymaps with special hardware needs
// install their own.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_install_platform_r(asdf_t *kb, const asdf_platform_t *platform) {
    kb->platform = platform ? platform : kb->base_platform;
    kb->outputs.physical.platform = kb->platform;
}

// PROCEDURE: asdf_set_strobe_polarity_r
// INPUTS: (asdf_t *) kb - keyboard
//         (uint8_t) positive - nonzero for a positive (idle low) strobe
// OUTPUTS: none
//
// DESCRIPTION: Sets the output strobe polarity through the keyboard's
// platform.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_set_strobe_polarity_r(asdf_t *kb, uint8_t positive) {
    kb->platform->set_strobe_polarity(kb->platform->user, positive);
}

// PROCEDURE: asdf_send_code_r
// INPUTS: (asdf_t *) kb - keyboard
//         (asdf_keycode_t) code - code to send to the host
// OUTPUTS: none
//
// DESCRIPTION: Sends a code to the host through the keyboard's platform.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_send_code_r(asdf_t *kb, asdf_keycode_t code) {
    kb->platform->send_code(kb->platform->user, code);
}

// PROCEDURE: asdf_next_code_r
// INPUTS: (asdf_t *) kb - keyboard
//         (asdf_keycode_t *) code - receives the code
// OUTPUTS: returns TRUE (nonzero) if a code was taken from the buffers into
// *code, FALSE (0) if none is ready.
//
// DESCRIPTION: Checks the message buffer, and returns a character
// if present.  Otherwise, return the next code in the keycode
// buffer.
//
// NOTES: After each system message character, output pauses for
// print_delay_ms ticks, to reduce the risk of dropped characters with
// unbuffered polling hosts. The pause is counted down by asdf_tick_r(), so it
// does not block scanning. No delay is needed for typed keycodes, as these are
// generated at human speeds.
//
// SCOPE: public
//
// COMPLEXITY: 3
//
uint8_t asdf_next_code_r(asdf_t *kb, asdf_keycode_t *code) {
    if (kb->output_wait_ms) {
        return 0;
    }
    if (asdf_ring_get(&kb->messages, code)) {
        kb->output_wait_ms = kb->print_delay_ms;
        return 1;
    }
    return asdf_ring_get(&kb->keycodes, code);
}

// PROCEDURE: asdf_tick_r
// INPUTS: (asdf_t *) kb - keyboard
//         (uint8_t) elapsed_ms - ticks (ms) elapsed
// OUTPUTS: none
//
// DESCRIPTION: Advances the keyboard's timers: the pause after a system
// message character, and long output pulses.
//
// SCOPE: public
//
// COMPLEXITY: 2
//
void asdf_tick_r(asdf_t *kb, uint8_t elapsed_ms) {
    kb->output_wait_ms = (kb->output_wait_ms > elapsed_ms) ? kb->output_wait_ms - elapsed_ms : 0;
    asdf_virtual_tick_r(&kb->outputs, elapsed_ms);
}

// PROCEDURE: asdf_process_r
// INPUTS: (asdf_t *) kb - keyboard
//         (uint16_t) elapsed_ms - ticks (ms) elapsed since the last call
// OUTPUTS: none
//
// DESCRIPTION: Runs the keyboard for the elapsed ticks: advance the timers by
// the elapsed ticks, send up to one code per elapsed tick (subject to message
// pacing), and scan the key matrix once, advancing debounce and repeat by the
// elapsed ticks. Timing therefore follows real time even if a scan takes
// longer than a tick.
//
// NOTES: Never blocks. Callers on a 1 ms tick call this with the ticks counted
// since the last call (see the platform adapter's asdf_arch_tick()). Elapsed
// times above 255 ticks are treated as 255.
//
// SCOPE: public
//
// COMPLEXITY: 4
//
void asdf_process_r(asdf_t *kb, uint16_t elapsed_ms) {
    uint8_t elapsed = (elapsed_ms > UINT8_MAX) ? UINT8_MAX : (uint8_t)elapsed_ms;

    if (!elapsed) {
        return;
    }

    asdf_tick_r(kb, elapsed);

    // send up to one code per elapsed tick, subject to message pacing
    asdf_keycode_t code;
    for (uint8_t n = elapsed; n && asdf_next_code_r(kb, &code); n--) {
        asdf_send_code_r(kb, code);
    }

    asdf_scan_elapsed_r(kb, elapsed);
}

// PROCEDURE: asdf_update_r
// INPUTS: (asdf_t *) kb - keyboard
//         (uint16_t) elapsed_ms - ticks (ms) elapsed since the last call
// OUTPUTS: none
//
// DESCRIPTION: Like asdf_process_r(), but sends nothing: advances the timers
// and scans the key matrix, leaving codes queued for the caller to take with
// asdf_next_code_r(). For applications that deliver codes themselves.
//
// NOTES: Never blocks. Elapsed times above 255 ticks are treated as 255.
//
// SCOPE: public
//
// COMPLEXITY: 2
//
void asdf_update_r(asdf_t *kb, uint16_t elapsed_ms) {
    uint8_t elapsed = (elapsed_ms > UINT8_MAX) ? UINT8_MAX : (uint8_t)elapsed_ms;

    if (elapsed) {
        asdf_tick_r(kb, elapsed);
        asdf_scan_elapsed_r(kb, elapsed);
    }
}

// PROCEDURE: asdf_sync_lock_leds_r
// INPUTS: (asdf_t *) kb - keyboard
// OUTPUTS: none
//
// DESCRIPTION: Drives the SHIFTLOCK (VSHIFT_LED) and CAPSLOCK (VCAPS_LED)
// indicators from the keyboard's modifier state.
//
// SCOPE: public
//
// COMPLEXITY: 3
//
void asdf_sync_lock_leds_r(asdf_t *kb) {
    asdf_virtual_action_r(&kb->outputs, VSHIFT_LED,
                          asdf_modifier_shift_locked_r(&kb->modifiers) ? V_SET_HI : V_SET_LO);
    asdf_virtual_action_r(&kb->outputs, VCAPS_LED,
                          asdf_modifier_caps_locked_r(&kb->modifiers) ? V_SET_HI : V_SET_LO);
}

// PROCEDURE: asdf_lookup_key_r
// INPUTS: (const asdf_t *) kb - keyboard; (uint8_t) row, col - key position
// OUTPUTS: returns the key at the position in the keymap for the current
//          modifier state.
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static asdf_key_t asdf_lookup_key_r(const asdf_t *kb, uint8_t row, uint8_t col) {
    return asdf_keymaps_get_key_r(&kb->keymap, row, col, asdf_modifier_index_r(&kb->modifiers));
}

// PROCEDURE: asdf_forget_repeat_key
// INPUTS: (asdf_t *) kb - keyboard
// OUTPUTS: none
//
// DESCRIPTION: There is no longer a repeating key.
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static void asdf_forget_repeat_key(asdf_t *kb) {
    kb->repeat_key = (asdf_key_t)KEY_NOTHING(0);
    kb->repeat_armed = 0;
    kb->last_key_row = NO_KEY_POSITION;
    kb->last_key_col = NO_KEY_POSITION;
}

// PROCEDURE: asdf_activate_key
// INPUTS: (asdf_t *) kb - keyboard
//         (asdf_key_t) key - the pressed key
//         (uint8_t) row, col - the position of the pressed key
// OUTPUTS: none
//
// DESCRIPTION: Performs the key's press action. If the action armed repeat
// (asdf_arm_repeat_r), the key becomes the repeating key, restarting the
// repeat timer if it is a different key from the last one.
//
// SCOPE: private
//
// COMPLEXITY: 3
//
static void asdf_activate_key(asdf_t *kb, asdf_key_t key, uint8_t row, uint8_t col) {
    kb->repeat_armed = 0;
    asdf_action_r(kb, key.press_fn, key.press_param);
    if (kb->repeat_armed) {
        kb->repeat_armed = 0;
        kb->repeat_key = key;
        if (row != kb->last_key_row || col != kb->last_key_col) {
            kb->last_key_row = row;
            kb->last_key_col = col;
            asdf_repeat_reset_count_r(&kb->repeat);
        }
    }
}

// PROCEDURE: asdf_arm_repeat_r
// INPUTS: (asdf_t *) kb - keyboard
// OUTPUTS: none
//
// DESCRIPTION: Called by a press action to make the key being pressed the
// repeating key.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_arm_repeat_r(asdf_t *kb) { kb->repeat_armed = 1; }

// PROCEDURE: asdf_same_key
// INPUTS: (asdf_key_t) a, b - keys to compare
// OUTPUTS: returns TRUE (nonzero) if the keys have the same actions and
//          parameters
//
// SCOPE: private
//
// COMPLEXITY: 1
//
static uint8_t asdf_same_key(asdf_key_t a, asdf_key_t b) {
    return a.press_fn == b.press_fn && a.press_param == b.press_param &&
           a.release_fn == b.release_fn && a.release_param == b.release_param;
}

// PROCEDURE: asdf_deactivate_key
// INPUTS: (asdf_t *) kb - keyboard
//         (asdf_key_t) key - the released key
//         (uint8_t) row, col - the position of the released key
// OUTPUTS: none
//
// DESCRIPTION: Performs the key's release action. If the released key is the
// repeating key, there is no longer a repeating key.
//
// SCOPE: private
//
// COMPLEXITY: 2
//
static void asdf_deactivate_key(asdf_t *kb, asdf_key_t key, uint8_t row, uint8_t col) {
    asdf_action_r(kb, key.release_fn, key.release_param);
    if (row == kb->last_key_row && col == kb->last_key_col) {
        asdf_forget_repeat_key(kb);
    }
}

// PROCEDURE: asdf_handle_key_press_or_release
// INPUTS: (asdf_t *) kb - keyboard
//         (uint8_t) row, col: The row and column number of the key that has
//         changed.
//         (uint8_t) key_was_pressed: TRUE if the key is now pressed.
// OUTPUTS: none
//
// DESCRIPTION: Debounces a key whose raw state differs from its stable state.
// After ASDF_DEBOUNCE_TIME_MS consecutive scans in the new state, the new state
// becomes stable and the key is activated or deactivated.
//
// NOTES: The debounce counter counts down from ASDF_DEBOUNCE_TIME_MS and is
// reloaded when it expires, so it is never decremented below 1. A key that
// returns to its stable state before debouncing has its counter reloaded by
// asdf_keyscan_r(), so a glitch does not shorten the next press.
//
// SCOPE: private
//
// COMPLEXITY: 3
//
static void asdf_handle_key_press_or_release(asdf_t *kb, uint8_t row, uint8_t col,
                                             uint8_t key_was_pressed, uint8_t elapsed) {
    uint8_t *debounce_count = &kb->debounce[row][col];

    if (*debounce_count > elapsed) {
        *debounce_count -= elapsed;
        return;
    }

    // debounce timed out. Set new stable state and activate or deactivate key.
    *debounce_count = ASDF_DEBOUNCE_TIME_MS;
    if (key_was_pressed) {
        kb->stable_rows[row] |= (asdf_cols_t)(1 << col);
        asdf_activate_key(kb, asdf_lookup_key_r(kb, row, col), row, col);
    } else {
        kb->stable_rows[row] &= (asdf_cols_t) ~(1 << col);
        asdf_deactivate_key(kb, asdf_lookup_key_r(kb, row, col), row, col);
    }
}

// PROCEDURE: asdf_handle_key_held_pressed
// INPUTS: (asdf_t *) kb - keyboard
//         (uint8_t) row, col: The row and column number of a key that is held
//         down (stable pressed state)
// OUTPUTS: none
//
// DESCRIPTION: If the key is the repeating key, and is still the same key
// under the current modifiers, advance the repeat timer and run its press
// action again when it expires.
//
// SCOPE: private
//
// COMPLEXITY: 4
//
static void asdf_handle_key_held_pressed(asdf_t *kb, uint8_t row, uint8_t col,
                                         uint8_t elapsed) {
    if (row != kb->last_key_row || col != kb->last_key_col) {
        return;
    }

    asdf_key_t key = asdf_lookup_key_r(kb, row, col);
    if (asdf_same_key(key, kb->repeat_key) && asdf_repeat_advance_r(&kb->repeat, elapsed)) {
        asdf_action_r(kb, key.press_fn, key.press_param);
        kb->repeat_armed = 0; // already the repeating key
    }
}

// PROCEDURE: asdf_scan_elapsed_r
// INPUTS: (asdf_t *) kb - keyboard
//         (uint8_t) elapsed - ticks elapsed since the previous scan
// OUTPUTS: none
//
// DESCRIPTION: Scans the key matrix. Debounce counters and the repeat timer
// advance by the elapsed ticks, so they keep real time however often the
// matrix is scanned. For each row, read the columns and compare
// with last stable state. For each changed key, call a key-change handler
// function. For each stable pressed key, call a "continued press" handler
// function. The keymap's each-scan action, if any, runs first. Finally, apply
// any keymap change requested during the scan.
//
// NOTES: 1) The keyboard state is stored as an array of words, with one word
//           per row, and each bit in a word representing one key in the row.
//
//        2) The whole scan uses the platform current at its start.
//
//        3) A key first seen changed after a gap of several ticks is assumed to
//           have been in its new state for the whole gap.
//
// SCOPE: private
//
// COMPLEXITY: 5
//
static void asdf_scan_elapsed_r(asdf_t *kb, uint8_t elapsed) {
    const asdf_platform_t *scan_platform = kb->platform;

    if (kb->keymap.each_scan) {
        asdf_action_r(kb, kb->keymap.each_scan, 0);
    }
    for (uint8_t row = 0;
         row < asdf_keymaps_num_rows_r(&kb->keymap, asdf_modifier_index_r(&kb->modifiers));
         row++) {
        asdf_cols_t row_key_state = scan_platform->read_row(scan_platform->user, row);
        asdf_cols_t changed = row_key_state ^ kb->stable_rows[row];

        for (uint8_t col = 0;
             col < asdf_keymaps_num_cols_r(&kb->keymap, asdf_modifier_index_r(&kb->modifiers));
             col++) {
            if (changed & 1) {
                // key state is different from last stable state
                asdf_handle_key_press_or_release(kb, row, col, row_key_state & 1, elapsed);
            } else {
                // key is in its stable state: restart any debounce in progress
                kb->debounce[row][col] = ASDF_DEBOUNCE_TIME_MS;
                if (row_key_state & 1) {
                    asdf_handle_key_held_pressed(kb, row, col, elapsed);
                }
            }
            changed >>= 1;
            row_key_state >>= 1;
        }
    }

    // Apply any keymap change requested during this scan.
    asdf_keymaps_apply_request_r(kb);
}

// PROCEDURE: asdf_keyscan_r
// INPUTS: (asdf_t *) kb - keyboard
// OUTPUTS: none
//
// DESCRIPTION: Scans the key matrix once, for one elapsed tick.
//
// SCOPE: public
//
// COMPLEXITY: 1
//
void asdf_keyscan_r(asdf_t *kb) { asdf_scan_elapsed_r(kb, 1); }

// PROCEDURE: asdf_apply_configuration_r
// INPUTS: (asdf_t *) kb - keyboard
// OUTPUTS: none
//
// DESCRIPTION: Called after a keymap switch has reset the keyboard state.
// Forgets the repeating key, then re-applies the press actions of held keys
// that are configuration actions (see asdf_is_configuration_action), such as
// DIP switches, so that settings such
// as DIP switches persist across keymap changes. Other held keys are not
// re-activated; they take effect again only when released and pressed.
//
// NOTES: Uses the last stable key state rather than rescanning.
//
// SCOPE: public
//
// COMPLEXITY: 4
//
void asdf_apply_configuration_r(asdf_t *kb) {
    modifier_index_t mods = asdf_modifier_index_r(&kb->modifiers);

    asdf_forget_repeat_key(kb);

    for (uint8_t row = 0; row < asdf_keymaps_num_rows_r(&kb->keymap, mods); row++) {
        asdf_cols_t row_key_state = kb->stable_rows[row];

        for (uint8_t col = 0; col < asdf_keymaps_num_cols_r(&kb->keymap, mods); col++) {
            if (row_key_state & 1) {
                asdf_key_t key = asdf_lookup_key_r(kb, row, col);
                if (asdf_is_configuration_action(key.press_fn)) {
                    asdf_action_r(kb, key.press_fn, key.press_param);
                }
            }
            row_key_state >>= 1;
        }
    }
}

// PROCEDURE: asdf_init_r
// INPUTS: (asdf_t *) kb - keyboard to initialize
//         (const asdf_platform_t *) platform - its hardware
// OUTPUTS: none
//
// DESCRIPTION: Initializes every part of the keyboard: empty output queues, no
// keys pressed, debounce counters reloaded, and keymap 0 selected (which also
// resets modifiers, repeat, the each-scan action, and outputs). May be called again to reset
// the keyboard.
//
// NOTES: The key state is cleared before keymap selection, so that keys held
// before a re-initialization are not treated as held configuration.
//
// SCOPE: public
//
// COMPLEXITY: 3
//
void asdf_init_r(asdf_t *kb, const asdf_platform_t *platform) {
    asdf_ring_init(&kb->keycodes, kb->keycode_storage, ASDF_KEYCODE_BUFFER_SIZE);
    asdf_ring_init(&kb->messages, kb->message_storage, ASDF_MESSAGE_BUFFER_SIZE);
    kb->print_delay_ms = 0;
    kb->output_wait_ms = 0;

    asdf_forget_repeat_key(kb);
    for (uint8_t row = 0; row < ASDF_MAX_ROWS; row++) {
        kb->stable_rows[row] = 0;
        for (uint8_t col = 0; col < ASDF_MAX_COLS; col++) {
            kb->debounce[row][col] = ASDF_DEBOUNCE_TIME_MS;
        }
    }

    kb->base_platform = platform;
    asdf_install_platform_r(kb, NULL);

    asdf_keymaps_init_r(kb);
}

//-------|---------|---------+---------+---------+---------+---------+---------+
// Above line is 80 columns, and should display completely in the editor.
