// -*- mode: C; tab-width: 4 ; indent-tabs-mode: nil -*-
//
// Universal Keyboard Project
// ASDF keyboard firmware
//
// asdf.h
//
// Copyright 2019 David Fenyes
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.
//

#if !defined(ASDF_H)
#define ASDF_H

#include <stdio.h>
#include <stdint.h>

// Returned by asdf_next_code() when no code is ready. Every 8-bit value is a
// valid code, so this is outside their range.
#define ASDF_INVALID_CODE 0x100

// define ASDF_MAX_COLS to fit in asdf_cols_t
#define ASDF_MAX_COLS 8
#define ASDF_MAX_ROWS 16

// for efficiency on 8-bit machines, use 8 columns per row. For 16 columns per
// row, change cols_t to uint16_t and increase ASDF_NUM_COLS to 16.
typedef uint8_t asdf_cols_t;

// A code sent to the host: any 8-bit value. Key actions are separate from
// codes (see asdf_actions.h).
typedef uint8_t asdf_keycode_t;

// One keyboard: all of its changeable state (defined in asdf_keyboard.h).
typedef struct asdf_keyboard asdf_t;


struct asdf_platform; // asdf_platform.h

// PROCEDURE: asdf_init
// INPUTS: (const struct asdf_platform *) platform - the keyboard's hardware,
//         such as the platform embedded in the architecture adapter's state
// OUTPUTS: none
// DESCRIPTION: initialize the keyboard state and debounce counters
void asdf_init(const struct asdf_platform *platform);

// PROCEDURE: asdf_process
// INPUTS: (uint16_t) elapsed_ms - ticks elapsed since the last call
// OUTPUTS: none
// DESCRIPTION: Runs the keyboard for the elapsed ticks: advance timers, send
// up to one code per tick, and scan once with debounce and repeat advanced by
// the elapsed ticks. Never blocks.
void asdf_process(uint16_t elapsed_ms);

// PROCEDURE: asdf_tick
// INPUTS: (uint8_t) elapsed_ms - ticks elapsed
// OUTPUTS: none
// DESCRIPTION: Advances the timers (message pacing, long output pulses)
// without scanning or sending.
void asdf_tick(uint8_t elapsed_ms);

// PROCEDURE: asdf_keyscan
// INPUTS: none
// OUTPUTS: none
// DESCRIPTION: Scans the key matrix. For each row, read the columns and compare
// with last stable state. For each changed key, call a key-change handler
// function. For each stable pressed key, call a "continued press" handler
// function.
void asdf_keyscan(void);

// PROCEDURE: asdf_apply_configuration
// INPUTS: none
// OUTPUTS: none
// DESCRIPTION: After a keymap switch resets the keyboard state, re-applies the
// configuration actions (keymap select, strobe polarity, autorepeat select) of
// held switches such as DIP switches, so configuration persists across keymap
// changes. Other held keys are not re-activated.
void asdf_apply_configuration(void);

// PROCEDURE: asdf_send_code
// INPUTS: (asdf_keycode_t) code: code to send to the host
// OUTPUTS: none
// DESCRIPTION: Sends a code to the host through the current platform (see
// asdf_platform.h).
void asdf_send_code(asdf_keycode_t code);

// PROCEDURE: asdf_put_code
// INPUTS: (asdf_keycode_t) code: code to be buffered for output
// OUTPUTS: returns TRUE (nonzero) if queued, FALSE (0) if the queue was full
// DESCRIPTION: Takes a keycode argument and buffers for output.
// NOTES: If the queue is full, the code is dropped and counted.
uint8_t asdf_put_code(asdf_keycode_t code);

// PROCEDURE: asdf_putc
// INPUTS: (char) c: character to be buffered for output
//         (FILE*) stream: only for prototype matching
// OUTPUTS: returns c, or EOF if the message queue had no room for it
// DESCRIPTION: Takes a character generated by the system and buffers for
// output. A newline is sent as CR LF, queued as a unit: either both fit or
// neither is queued.
int asdf_putc(char c, FILE *stream);

// PROCEDURE: asdf_next_code
// INPUTS: none
// OUTPUTS: returns the next code in the buffers, or ASDF_INVALID_CODE if none
// is ready.
// DESCRIPTION: Checks the message buffer, and returns a character
// if present.  Otherwise, return the next code in the keycode
// buffer.
// NOTES: A delay is enforced for system messages, to reduce the risk of dropped
// characters with unbuffered polling hosts. No delay is needed for typed
// keycodes, as these are generated at human speeds.
uint16_t asdf_next_code(void);

// PROCEDURE: asdf_set_print_delay
// INPUTS: (uint8_t) delay_ms
// OUTPUTS: none
// DESCRIPTION: sets the delay to be used by the system print buffer
// NOTES: A delay is enforced for system messages, to reduce the risk of dropped
// characters with unbuffered polling hosts. No delay is needed for typed
// keycodes, as these are generated at human speeds.
void asdf_set_print_delay(uint8_t delay_ms);

#endif // !defined (ASDF_H)


//-------|---------|---------+---------+---------+---------+---------+---------+
// Above line is 80 columns, and should display completely in the editor.
