// -*- mode: C; tab-width: 2 ; indent-tabs-mode: nil -*-
//
//  Universal Keyboard Project
//  ASDF firmware - small, fast, and simple keyboard encoder.
//
//  asdf.c
//
// This file contains code for:
// - the main scan code and key handler routines
// - key debouncing and autorepeat of the held key
// - the keyboard's output queues and message pacing
// - initialization of the keyboard object
//
// Copyright 2019 David Fenyes
//
//  This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

#include "asdf.h"
#include "asdf_arch.h"
#include "asdf_ascii.h"
#include "asdf_ring.h"
#include "asdf_platform.h"
#include "asdf_actions.h"
#include "asdf_keyboard.h"
#include "asdf_keymaps.h"
#include "asdf_modifiers.h"
#include "asdf_physical.h"
#include "asdf_repeat.h"
#include "asdf_virtual.h"
#include <stdint.h>
#include <stdio.h>

// All keyboard state is held in the asdf_t passed to each function. The public
// contracts are in asdf_keyboard.h.

// Position of no key, for last_key_row/last_key_col when no key is repeating.
#define NO_KEY_POSITION 0xff

static void asdf_scan_elapsed_r(asdf_t *kb, uint8_t elapsed);

/**
 * Buffer a typed keycode for output.
 *
 * Appends the code to the keyboard's keycode queue. If the queue is full, the
 * code is dropped and counted.
 *
 * @param kb    Keyboard.
 * @param code  Code to be buffered for output.
 * @return 1 if the code was queued; 0 if the keycode queue was full.
 */
uint8_t asdf_put_code_r(asdf_t *kb, asdf_keycode_t code) {
    return asdf_ring_put(&kb->keycodes, code);
}

/**
 * Count the typed keycodes dropped because the keycode queue was full.
 *
 * No side effects.
 *
 * @param kb  Keyboard.
 * @return Codes dropped since initialization, saturating at 255.
 */
uint8_t asdf_dropped_codes_r(const asdf_t *kb) { return asdf_ring_dropped(&kb->keycodes); }

/**
 * Count the system message characters dropped because the message queue was
 * full.
 *
 * No side effects.
 *
 * @param kb  Keyboard.
 * @return Characters dropped since initialization, saturating at 255.
 */
uint8_t asdf_dropped_messages_r(const asdf_t *kb) { return asdf_ring_dropped(&kb->messages); }

/**
 * Count the entries of the current keymap's descriptor that could not be
 * applied.
 *
 * No side effects.
 *
 * @param kb  Keyboard.
 * @return Failed entries, saturating at 255; 0 for a correct keymap.
 */
uint8_t asdf_keymap_errors_r(const asdf_t *kb) { return kb->keymap.errors; }

/**
 * Buffer a character generated by the system for output.
 *
 * Appends the character to the keyboard's message queue; a newline is queued
 * as CR LF. Characters that do not fit are dropped and counted.
 *
 * @param kb  Keyboard.
 * @param c   Character to be buffered for output.
 * @return @p c if queued; EOF if the message queue had no room for it.
 *
 * CR LF is queued as a unit: if both do not fit, neither is queued, so a
 * message never ends with a partial line ending.
 *
 * Complexity: 3
 */
int asdf_putc_r(asdf_t *kb, char c) {
    uint8_t queued = ('\n' == c) ? asdf_ring_put_pair(&kb->messages, '\r', '\n')
                                 : asdf_ring_put(&kb->messages, (asdf_keycode_t)c);
    return queued ? (int)c : EOF;
}

/**
 * Select the platform through which the key matrix is read, codes are sent,
 * and outputs are driven.
 *
 * Sets the keyboard's platform and the physical outputs' platform. Keymaps
 * with special hardware needs install their own.
 *
 * @param kb        Keyboard.
 * @param platform  Platform to use, or NULL for the keyboard's base platform.
 *
 * Complexity: 2
 */
void asdf_install_platform_r(asdf_t *kb, const asdf_platform_t *platform) {
    kb->platform = platform ? platform : kb->base_platform;
    kb->outputs.physical.platform = kb->platform;
}

/**
 * Set the output strobe polarity through the keyboard's platform.
 *
 * Drives the strobe through the platform.
 *
 * @param kb        Keyboard.
 * @param positive  Nonzero for a positive (idle low) strobe; 0 for negative.
 */
void asdf_set_strobe_polarity_r(asdf_t *kb, uint8_t positive) {
    kb->platform->set_strobe_polarity(kb->platform->user, positive);
}

/**
 * Send a code to the host through the keyboard's platform, immediately.
 *
 * Drives the output through the platform.
 *
 * @param kb    Keyboard.
 * @param code  Code to send to the host.
 */
void asdf_send_code_r(asdf_t *kb, asdf_keycode_t code) {
    kb->platform->send_code(kb->platform->user, code);
}

/**
 * Take the next code to send to the host.
 *
 * Checks the message queue, and takes a character if one is present;
 * otherwise takes the next code in the keycode queue. Taking a message
 * character starts the output pause.
 *
 * @param kb    Keyboard.
 * @param code  Receives the code; not written when none is taken.
 * @return 1 if a code was taken into @p code; 0 if none is queued or output is
 *         paused after a message character.
 *
 * After each system message character, output pauses for print_delay_ms
 * ticks, to reduce the risk of dropped characters with unbuffered polling
 * hosts. The pause is counted down by asdf_tick_r(), so it does not block
 * scanning. No delay is needed for typed keycodes, as these are generated at
 * human speeds.
 *
 * Complexity: 3
 */
uint8_t asdf_next_code_r(asdf_t *kb, asdf_keycode_t *code) {
    if (kb->output_wait_ms) {
        return 0;
    }
    if (asdf_ring_get(&kb->messages, code)) {
        kb->output_wait_ms = kb->print_delay_ms;
        return 1;
    }
    return asdf_ring_get(&kb->keycodes, code);
}

/**
 * Advance the keyboard's timers without scanning or sending.
 *
 * Counts down the pause after a system message character, stopping at 0, and
 * advances any long output pulses, which may drive outputs through the
 * platform.
 *
 * @param kb          Keyboard.
 * @param elapsed_ms  1 ms ticks elapsed.
 *
 * Complexity: 2
 */
void asdf_tick_r(asdf_t *kb, uint8_t elapsed_ms) {
    kb->output_wait_ms = (kb->output_wait_ms > elapsed_ms) ? kb->output_wait_ms - elapsed_ms : 0;
    asdf_virtual_tick_r(&kb->outputs, elapsed_ms);
}

/**
 * Run the keyboard for the ticks elapsed since the last call.
 *
 * Advances the timers by the elapsed ticks, sends up to one queued code per
 * elapsed tick through the platform (subject to message pacing), and scans
 * the key matrix once, advancing debounce and repeat by the elapsed ticks.
 * Key actions run by the scan may queue codes, change modifiers, and drive
 * outputs. Does nothing if @p elapsed_ms is 0.
 *
 * @param kb          Keyboard.
 * @param elapsed_ms  1 ms ticks elapsed since the last call; values above 255
 *                    are treated as 255.
 *
 * Never blocks. Timing follows real time even if a scan takes longer than a
 * tick. Callers on a 1 ms tick pass the ticks counted since the last call
 * (see the platform adapter's asdf_arch_tick()).
 *
 * Complexity: 5
 */
void asdf_process_r(asdf_t *kb, uint16_t elapsed_ms) {
    uint8_t elapsed = (elapsed_ms > UINT8_MAX) ? (uint8_t)UINT8_MAX : (uint8_t)elapsed_ms;

    if (!elapsed) {
        return;
    }

    asdf_tick_r(kb, elapsed);

    // send up to one code per elapsed tick, subject to message pacing
    asdf_keycode_t code;
    for (uint8_t n = elapsed; n && asdf_next_code_r(kb, &code); n--) {
        asdf_send_code_r(kb, code);
    }

    asdf_scan_elapsed_r(kb, elapsed);
}

/**
 * Run the keyboard like asdf_process_r(), but send nothing.
 *
 * Advances the timers and scans the key matrix once, leaving codes queued for
 * the caller to take with asdf_next_code_r(). For applications that deliver
 * codes themselves. Key actions run by the scan may queue codes, change
 * modifiers, and drive outputs. Does nothing if @p elapsed_ms is 0.
 *
 * @param kb          Keyboard.
 * @param elapsed_ms  1 ms ticks elapsed since the last call; values above 255
 *                    are treated as 255.
 *
 * Never blocks.
 *
 * Complexity: 3
 */
void asdf_update_r(asdf_t *kb, uint16_t elapsed_ms) {
    uint8_t elapsed = (elapsed_ms > UINT8_MAX) ? (uint8_t)UINT8_MAX : (uint8_t)elapsed_ms;

    if (elapsed) {
        asdf_tick_r(kb, elapsed);
        asdf_scan_elapsed_r(kb, elapsed);
    }
}

/**
 * Drive the SHIFTLOCK and CAPSLOCK indicators from the modifier state.
 *
 * Sets VSHIFT_LED and VCAPS_LED high if the corresponding lock is on, else
 * low, driving the outputs through the platform.
 *
 * @param kb  Keyboard.
 *
 * Complexity: 3
 */
void asdf_sync_lock_leds_r(asdf_t *kb) {
    asdf_virtual_action_r(&kb->outputs, VSHIFT_LED,
                          asdf_modifier_shift_locked_r(&kb->modifiers) ? V_SET_HI : V_SET_LO);
    asdf_virtual_action_r(&kb->outputs, VCAPS_LED,
                          asdf_modifier_caps_locked_r(&kb->modifiers) ? V_SET_HI : V_SET_LO);
}

/**
 * Look up a key in the current keymap under the current modifiers.
 *
 * No side effects.
 *
 * @param kb   Keyboard.
 * @param row  Key row.
 * @param col  Key column.
 * @return The key at @p row, @p col.
 */
static asdf_key_t asdf_lookup_key_r(const asdf_t *kb, uint8_t row, uint8_t col) {
    return asdf_keymaps_get_key_r(&kb->keymap, row, col, asdf_modifier_index_r(&kb->modifiers));
}

/**
 * Forget the repeating key, so that no key repeats.
 *
 * Clears the repeating key, its position, and the repeat-armed flag.
 *
 * @param kb  Keyboard.
 */
static void asdf_forget_repeat_key(asdf_t *kb) {
    kb->repeat_key = (asdf_key_t)KEY_NOTHING(0);
    kb->repeat_armed = 0;
    kb->last_key_row = NO_KEY_POSITION;
    kb->last_key_col = NO_KEY_POSITION;
}

/**
 * Run a pressed key's press action.
 *
 * Runs the action, with whatever effects it has. If the action armed repeat
 * (asdf_arm_repeat_r()), the key becomes the repeating key; the repeat timer
 * restarts only if it is at a different position from the last repeating key.
 *
 * @param kb   Keyboard.
 * @param key  The pressed key.
 * @param row  Row of the pressed key.
 * @param col  Column of the pressed key.
 *
 * Complexity: 4
 */
static void asdf_activate_key(asdf_t *kb, asdf_key_t key, uint8_t row, uint8_t col) {
    kb->repeat_armed = 0;
    asdf_action_r(kb, key.press_fn, key.press_param);
    if (kb->repeat_armed) {
        kb->repeat_armed = 0;
        kb->repeat_key = key;
        if (row != kb->last_key_row || col != kb->last_key_col) {
            kb->last_key_row = row;
            kb->last_key_col = col;
            asdf_repeat_reset_count_r(&kb->repeat);
        }
    }
}

/**
 * Make the key being pressed the repeating key.
 *
 * Called by a press action. Sets the repeat-armed flag, which
 * asdf_activate_key() consumes once the action returns.
 *
 * @param kb  Keyboard.
 */
void asdf_arm_repeat_r(asdf_t *kb) { kb->repeat_armed = 1; }

/**
 * Compare two keys.
 *
 * No side effects.
 *
 * @param a  First key.
 * @param b  Second key.
 * @return 1 if @p a and @p b have the same actions and parameters; else 0.
 *
 * Complexity: 4
 */
static uint8_t asdf_same_key(asdf_key_t a, asdf_key_t b) {
    return a.press_fn == b.press_fn && a.press_param == b.press_param &&
           a.release_fn == b.release_fn && a.release_param == b.release_param;
}

/**
 * Run a released key's release action.
 *
 * Runs the action, with whatever effects it has. If the released key is the
 * repeating key, no key repeats afterwards.
 *
 * @param kb   Keyboard.
 * @param key  The released key.
 * @param row  Row of the released key.
 * @param col  Column of the released key.
 *
 * Complexity: 3
 */
static void asdf_deactivate_key(asdf_t *kb, asdf_key_t key, uint8_t row, uint8_t col) {
    asdf_action_r(kb, key.release_fn, key.release_param);
    if (row == kb->last_key_row && col == kb->last_key_col) {
        asdf_forget_repeat_key(kb);
    }
}

/**
 * Debounce a key whose raw state differs from its stable state.
 *
 * Counts down the key's debounce counter. Once the key has been in its new
 * state for ASDF_DEBOUNCE_TIME_MS ticks, the new state becomes stable and the
 * key is activated or deactivated, running its press or release action.
 *
 * @param kb               Keyboard.
 * @param row              Row of the changed key.
 * @param col              Column of the changed key.
 * @param key_was_pressed  Nonzero if the key is now pressed.
 * @param elapsed          Ticks since the previous scan.
 *
 * The counter counts down from ASDF_DEBOUNCE_TIME_MS and is reloaded when it
 * expires, so it never falls below 1. A key that returns to its stable state
 * before debouncing has its counter reloaded by the scan, so a glitch does not
 * shorten the next press.
 *
 * Complexity: 3
 */
static void asdf_handle_key_press_or_release(asdf_t *kb, uint8_t row, uint8_t col,
                                             uint8_t key_was_pressed, uint8_t elapsed) {
    uint8_t *debounce_count = &kb->debounce[row][col];

    if (*debounce_count > elapsed) {
        *debounce_count -= elapsed;
        return;
    }

    // debounce timed out. Set new stable state and activate or deactivate key.
    *debounce_count = ASDF_DEBOUNCE_TIME_MS;
    if (key_was_pressed) {
        kb->stable_rows[row] |= (asdf_cols_t)(1 << col);
        asdf_activate_key(kb, asdf_lookup_key_r(kb, row, col), row, col);
    } else {
        kb->stable_rows[row] &= (asdf_cols_t) ~(1 << col);
        asdf_deactivate_key(kb, asdf_lookup_key_r(kb, row, col), row, col);
    }
}

/**
 * Repeat a key held in its stable pressed state, if it is the repeating key.
 *
 * If the key is the repeating key, and is still the same key under the
 * current modifiers, advances the repeat timer; when the timer expires, runs
 * the key's press action again.
 *
 * @param kb       Keyboard.
 * @param row      Row of the held key.
 * @param col      Column of the held key.
 * @param elapsed  Ticks since the previous scan.
 *
 * Complexity: 5
 */
static void asdf_handle_key_held_pressed(asdf_t *kb, uint8_t row, uint8_t col,
                                         uint8_t elapsed) {
    if (row != kb->last_key_row || col != kb->last_key_col) {
        return;
    }

    asdf_key_t key = asdf_lookup_key_r(kb, row, col);
    if (asdf_same_key(key, kb->repeat_key) && asdf_repeat_advance_r(&kb->repeat, elapsed)) {
        asdf_action_r(kb, key.press_fn, key.press_param);
        kb->repeat_armed = 0; // already the repeating key
    }
}

/**
 * Scan the key matrix once, advancing debounce and repeat by @p elapsed ticks.
 *
 * Runs the keymap's each-scan action, if any, first. Then, for each row,
 * reads the columns through the platform and compares them with the last
 * stable state: each changed key is debounced, and each stable pressed key is
 * checked for repeat. Finally applies any keymap change requested during the
 * scan. Key actions run by the scan may queue codes, change modifiers, drive
 * outputs, and switch keymaps.
 *
 * @param kb       Keyboard.
 * @param elapsed  Ticks since the previous scan.
 *
 * The key state is stored as an array of words, one word per row, one bit per
 * key. The whole scan uses the platform current at its start, so a keymap
 * that installs a platform mid-scan does not split the scan. Debounce counters
 * and the repeat timer advance by the elapsed ticks, so they keep real time
 * however often the matrix is scanned; a key first seen changed after a gap of
 * several ticks is taken to have been in its new state for the whole gap.
 *
 * Complexity: 6
 */
static void asdf_scan_elapsed_r(asdf_t *kb, uint8_t elapsed) {
    const asdf_platform_t *scan_platform = kb->platform;

    if (kb->keymap.each_scan) {
        asdf_action_r(kb, kb->keymap.each_scan, 0);
    }
    for (uint8_t row = 0;
         row < asdf_keymaps_num_rows_r(&kb->keymap, asdf_modifier_index_r(&kb->modifiers));
         row++) {
        asdf_cols_t row_key_state = scan_platform->read_row(scan_platform->user, row);
        asdf_cols_t changed = row_key_state ^ kb->stable_rows[row];

        for (uint8_t col = 0;
             col < asdf_keymaps_num_cols_r(&kb->keymap, asdf_modifier_index_r(&kb->modifiers));
             col++) {
            if (changed & 1) {
                asdf_handle_key_press_or_release(kb, row, col, row_key_state & 1, elapsed);
            } else {
                // key is in its stable state: restart any debounce in progress
                kb->debounce[row][col] = ASDF_DEBOUNCE_TIME_MS;
                if (row_key_state & 1) {
                    asdf_handle_key_held_pressed(kb, row, col, elapsed);
                }
            }
            changed >>= 1;
            row_key_state >>= 1;
        }
    }

    asdf_keymaps_apply_request_r(kb);
}

/**
 * Scan the key matrix once, for one elapsed tick.
 *
 * Debounces and acts on key changes, repeats the held repeating key, and
 * applies any keymap change requested during the scan. Key actions may queue
 * codes, change modifiers, and drive outputs.
 *
 * @param kb  Keyboard.
 */
void asdf_keyscan_r(asdf_t *kb) { asdf_scan_elapsed_r(kb, 1); }

/**
 * Re-apply held configuration switches after a keymap switch.
 *
 * Called after a keymap switch has reset the keyboard state. Forgets the
 * repeating key, then runs the press actions of held keys that are
 * configuration actions (see asdf_is_configuration_action()), such as DIP
 * switches, so their settings persist across keymap changes. Other held keys
 * are not re-activated; they take effect again only when released and
 * pressed.
 *
 * @param kb  Keyboard.
 *
 * Uses the last stable key state rather than rescanning.
 *
 * Complexity: 5
 */
void asdf_apply_configuration_r(asdf_t *kb) {
    modifier_index_t mods = asdf_modifier_index_r(&kb->modifiers);

    asdf_forget_repeat_key(kb);

    for (uint8_t row = 0; row < asdf_keymaps_num_rows_r(&kb->keymap, mods); row++) {
        asdf_cols_t row_key_state = kb->stable_rows[row];

        for (uint8_t col = 0; col < asdf_keymaps_num_cols_r(&kb->keymap, mods); col++) {
            if (row_key_state & 1) {
                asdf_key_t key = asdf_lookup_key_r(kb, row, col);
                if (asdf_is_configuration_action(key.press_fn)) {
                    asdf_action_r(kb, key.press_fn, key.press_param);
                }
            }
            row_key_state >>= 1;
        }
    }
}

/**
 * Initialize every part of the keyboard, or reset one already in use.
 *
 * Empties the output queues and ends any message pause, forgets all key state
 * (no keys pressed, no repeating key, debounce counters reloaded), installs
 * @p platform, and selects keymap 0, which also resets modifiers, repeat, the
 * each-scan action, and virtual outputs, and applies keymap 0's descriptor.
 *
 * @param kb        Keyboard to initialize.
 * @param platform  Its hardware; must not be NULL.
 *
 * Complexity: 3
 */
void asdf_init_r(asdf_t *kb, const asdf_platform_t *platform) {
    asdf_ring_init(&kb->keycodes, kb->keycode_storage, ASDF_KEYCODE_BUFFER_SIZE);
    asdf_ring_init(&kb->messages, kb->message_storage, ASDF_MESSAGE_BUFFER_SIZE);
    kb->print_delay_ms = 0;
    kb->output_wait_ms = 0;

    asdf_forget_repeat_key(kb);
    for (uint8_t row = 0; row < ASDF_MAX_ROWS; row++) {
        kb->stable_rows[row] = 0;
        for (uint8_t col = 0; col < ASDF_MAX_COLS; col++) {
            kb->debounce[row][col] = ASDF_DEBOUNCE_TIME_MS;
        }
    }

    kb->base_platform = platform;
    asdf_install_platform_r(kb, NULL);

    // The key state was cleared above, before keymap selection, so keys held
    // before a reset are not re-applied as held configuration.
    asdf_keymaps_init_r(kb);
}

//-------|---------|---------+---------+---------+---------+---------+---------+
// Above line is 80 columns, and should display completely in the editor.
